from .employees import EmployeeTypeC
from .employees import EmployeeStatusC
from .employees import EmployeeC
from .departments import DepartmentsC
from .products import FirmwareC
from .products import CategoriesC
from .products import ProductInfoC
from .products import DealerC
from .products import ProductStatusC
from .products import ProductC
from .clients import SubscriptionC
from .clients import ClientC